# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\tAuthToken\x12\x13\n\x0btoken_value\x18\x01 \x01(\t\"\x1c\n\x05Token\x12\x13\n\x0btoken_value\x18\x01 \x01(\t\"&\n\tTokenInfo\x12\x0b\n\x03sub\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x03(\t\"\"\n\x0fSuccessResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x91\x01\n\x0b\x41uthService\x12\x30\n\x10\x41uthenticateUser\x12\x10.UserCredentials\x1a\n.AuthToken\x12#\n\rValidateToken\x12\x06.Token\x1a\n.TokenInfo\x12+\n\x0fInvalidateToken\x12\x06.Token\x1a\x10.SuccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERCREDENTIALS']._serialized_start=15
  _globals['_USERCREDENTIALS']._serialized_end=68
  _globals['_AUTHTOKEN']._serialized_start=70
  _globals['_AUTHTOKEN']._serialized_end=102
  _globals['_TOKEN']._serialized_start=104
  _globals['_TOKEN']._serialized_end=132
  _globals['_TOKENINFO']._serialized_start=134
  _globals['_TOKENINFO']._serialized_end=172
  _globals['_SUCCESSRESPONSE']._serialized_start=174
  _globals['_SUCCESSRESPONSE']._serialized_end=208
  _globals['_AUTHSERVICE']._serialized_start=211
  _globals['_AUTHSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
